#pragma once

#include <QObject>
#include <QString>
#include <QDateTime>

namespace Models {

class Post : public QObject
{
    Q_OBJECT

    Q_PROPERTY(qint32 id READ id WRITE setId NOTIFY idChanged)
    Q_PROPERTY(QString title READ title WRITE setTitle NOTIFY titleChanged)
    Q_PROPERTY(QString content READ content WRITE setContent NOTIFY contentChanged)
    Q_PROPERTY(qint32 userId READ userId WRITE setUserId NOTIFY userIdChanged)
    Q_PROPERTY(QDateTime createdAt READ createdAt WRITE setCreatedAt NOTIFY createdAtChanged)

    Q_ORM_PROPERTY(id IDENTITY AUTOGENERATED)
    Q_ORM_PROPERTY(userId COLUMN user_id)
    Q_ORM_PROPERTY(createdAt COLUMN created_at)

public:
    Q_INVOKABLE explicit Post(QObject* parent = nullptr);
    
    qint32 id() const;
    void setId(const qint32& id);
    
    QString title() const;
    void setTitle(const QString& title);
    
    QString content() const;
    void setContent(const QString& content);
    
    qint32 userId() const;
    void setUserId(const qint32& userId);
    
    QDateTime createdAt() const;
    void setCreatedAt(const QDateTime& createdAt);

signals:
    void idChanged();
    void titleChanged();
    void contentChanged();
    void userIdChanged();
    void createdAtChanged();

private:
    qint32 m_id{0};
    QString m_title;
    QString m_content;
    qint32 m_userId{0};
    QDateTime m_createdAt;
};

} // namespace Models