#pragma once

#include <QObject>
#include <QString>
#include <QDateTime>

namespace Models {

class User : public QObject
{
    Q_OBJECT

    Q_PROPERTY(qint32 id READ id WRITE setId NOTIFY idChanged)
    Q_PROPERTY(QString username READ username WRITE setUsername NOTIFY usernameChanged)
    Q_PROPERTY(QString email READ email WRITE setEmail NOTIFY emailChanged)
    Q_PROPERTY(QDateTime createdAt READ createdAt WRITE setCreatedAt NOTIFY createdAtChanged)

    Q_ORM_PROPERTY(id IDENTITY AUTOGENERATED)
    Q_ORM_PROPERTY(createdAt COLUMN created_at)

public:
    Q_INVOKABLE explicit User(QObject* parent = nullptr);
    
    qint32 id() const;
    void setId(const qint32& id);
    
    QString username() const;
    void setUsername(const QString& username);
    
    QString email() const;
    void setEmail(const QString& email);
    
    QDateTime createdAt() const;
    void setCreatedAt(const QDateTime& createdAt);

signals:
    void idChanged();
    void usernameChanged();
    void emailChanged();
    void createdAtChanged();

private:
    qint32 m_id{0};
    QString m_username;
    QString m_email;
    QDateTime m_createdAt;
};

} // namespace Models