#include "qxormqtorm/codegen/sqlserverddlgenerator.h"
#include <QStringList>

namespace QxOrmQtOrm {

SqlServerDdlGenerator::SqlServerDdlGenerator()
{
    // Initialize default options
    m_options.includeDropStatements = false;
    m_options.includeIndexes = true;
    m_options.includeForeignKeys = true;
    m_options.includeComments = true;
    m_options.schemaName = "dbo";
    m_options.indent = "    ";
}

SqlServerDdlGenerator::SqlServerDdlGenerator(const DdlOptions& options)
    : m_options(options)
{
}

QString SqlServerDdlGenerator::generateDdl(const DatabaseSchema& schema)
{
    QStringList ddlStatements;
    
    // Database comment header
    if (!schema.databaseName.isEmpty()) {
        ddlStatements << QString("-- Generated DDL for database: %1").arg(schema.databaseName);
        ddlStatements << "-- Generated by QxOrm+QtOrm Integration Tool";
        ddlStatements << "";
    }
    
    // Drop statements (if requested)
    if (m_options.includeDropStatements) {
        ddlStatements << "-- Drop Tables";
        ddlStatements << "";
        
        // Drop in reverse order to handle foreign key dependencies
        for (auto it = schema.tables.rbegin(); it != schema.tables.rend(); ++it) {
            ddlStatements << generateDropTable(*it);
        }
        ddlStatements << "";
    }
    
    // Create table statements
    ddlStatements << "-- Create Tables";
    ddlStatements << "";
    
    for (const auto& table : schema.tables) {
        ddlStatements << generateCreateTable(table);
        ddlStatements << "";
    }
    
    // Foreign key constraints (if requested and separate from CREATE TABLE)
    if (m_options.includeForeignKeys) {
        QString foreignKeys = generateForeignKeys(schema.tables);
        if (!foreignKeys.isEmpty()) {
            ddlStatements << "-- Foreign Key Constraints";
            ddlStatements << "";
            ddlStatements << foreignKeys;
        }
    }
    
    return ddlStatements.join("\n");
}

QString SqlServerDdlGenerator::generateCreateTable(const TableDefinition& table)
{
    QStringList lines;
    
    // Table comment
    if (!table.comment.isEmpty() && m_options.includeComments) {
        lines << QString("-- %1").arg(table.comment);
    }
    
    // CREATE TABLE statement
    QString tableName = escapeIdentifier(table.name);
    if (!m_options.schemaName.isEmpty() && m_options.schemaName != "dbo") {
        tableName = escapeIdentifier(m_options.schemaName) + "." + tableName;
    }
    
    lines << QString("CREATE TABLE %1 (").arg(tableName);
    
    // Column definitions
    QStringList columnDefs;
    for (const auto& column : table.columns) {
        columnDefs << QString("%1%2").arg(m_options.indent, generateColumnDefinition(column));
    }
    
    // Primary key constraint
    QString primaryKeyConstraint = generatePrimaryKeyConstraint(table);
    if (!primaryKeyConstraint.isEmpty()) {
        columnDefs << QString("%1%2").arg(m_options.indent, primaryKeyConstraint);
    }
    
    lines << columnDefs.join(",\n");
    lines << ");";
    
    // Table comment as extended property
    if (!table.comment.isEmpty() && m_options.includeComments) {
        lines << "";
        lines << QString("EXEC sp_addextendedproperty");
        lines << QString("%1@name = N'MS_Description',").arg(m_options.indent);
        lines << QString("%1@value = N'%2',").arg(m_options.indent, QString(table.comment).replace("'", "''"));
        lines << QString("%1@level0type = N'SCHEMA',").arg(m_options.indent);
        lines << QString("%1@level0name = N'%2',").arg(m_options.indent, m_options.schemaName);
        lines << QString("%1@level1type = N'TABLE',").arg(m_options.indent);
        lines << QString("%1@level1name = N'%2';").arg(m_options.indent, table.name);
    }
    
    // Column comments as extended properties
    if (m_options.includeComments) {
        for (const auto& column : table.columns) {
            if (!column.comment.isEmpty()) {
                lines << "";
                lines << QString("EXEC sp_addextendedproperty");
                lines << QString("%1@name = N'MS_Description',").arg(m_options.indent);
                lines << QString("%1@value = N'%2',").arg(m_options.indent, QString(column.comment).replace("'", "''"));
                lines << QString("%1@level0type = N'SCHEMA',").arg(m_options.indent);
                lines << QString("%1@level0name = N'%2',").arg(m_options.indent, m_options.schemaName);
                lines << QString("%1@level1type = N'TABLE',").arg(m_options.indent);
                lines << QString("%1@level1name = N'%2',").arg(m_options.indent, table.name);
                lines << QString("%1@level2type = N'COLUMN',").arg(m_options.indent);
                lines << QString("%1@level2name = N'%2';").arg(m_options.indent, column.name);
            }
        }
    }
    
    return lines.join("\n");
}

QString SqlServerDdlGenerator::generateDropTable(const TableDefinition& table)
{
    QString tableName = escapeIdentifier(table.name);
    if (!m_options.schemaName.isEmpty() && m_options.schemaName != "dbo") {
        tableName = escapeIdentifier(m_options.schemaName) + "." + tableName;
    }
    
    return QString("DROP TABLE IF EXISTS %1;").arg(tableName);
}

QString SqlServerDdlGenerator::generateForeignKeys(const QVector<TableDefinition>& tables)
{
    QStringList constraints;
    
    for (const auto& table : tables) {
        for (const auto& column : table.columns) {
            if (column.isForeignKey) {
                QString constraintName = QString("FK_%1_%2_%3_%4")
                                        .arg(table.name, column.name, 
                                             column.referencedTable, column.referencedColumn);
                
                QString tableName = escapeIdentifier(table.name);
                QString refTableName = escapeIdentifier(column.referencedTable);
                
                if (!m_options.schemaName.isEmpty() && m_options.schemaName != "dbo") {
                    QString schema = escapeIdentifier(m_options.schemaName);
                    tableName = schema + "." + tableName;
                    refTableName = schema + "." + refTableName;
                }
                
                constraints << QString("ALTER TABLE %1").arg(tableName);
                constraints << QString("%1ADD CONSTRAINT %2").arg(m_options.indent, escapeIdentifier(constraintName));
                constraints << QString("%1FOREIGN KEY (%2)").arg(m_options.indent, escapeIdentifier(column.name));
                constraints << QString("%1REFERENCES %2 (%3);").arg(m_options.indent, refTableName, escapeIdentifier(column.referencedColumn));
                constraints << "";
            }
        }
    }
    
    return constraints.join("\n");
}

QString SqlServerDdlGenerator::mapQtTypeToSqlServer(const QString& qtType, int maxLength)
{
    if (qtType == "bool") return "BIT";
    if (qtType == "quint8") return "TINYINT";
    if (qtType == "qint16") return "SMALLINT";
    if (qtType == "qint32" || qtType == "int") return "INT";
    if (qtType == "qint64") return "BIGINT";
    if (qtType == "float") return "REAL";
    if (qtType == "double") return "FLOAT";
    if (qtType == "QDateTime") return "DATETIME2";
    if (qtType == "QDate") return "DATE";
    if (qtType == "QTime") return "TIME";
    if (qtType == "QByteArray") return "VARBINARY(MAX)";
    if (qtType == "QUuid") return "UNIQUEIDENTIFIER";
    
    // String types
    if (qtType == "QString") {
        if (maxLength > 0 && maxLength <= 4000) {
            return QString("NVARCHAR(%1)").arg(maxLength);
        } else {
            return "NVARCHAR(MAX)";
        }
    }
    
    // Default fallback
    return "NVARCHAR(255)";
}

QString SqlServerDdlGenerator::generateColumnDefinition(const ColumnDefinition& column)
{
    QStringList parts;
    
    // Column name
    parts << escapeIdentifier(column.name);
    
    // Data type
    QString sqlType = mapQtTypeToSqlServer(column.qtType, column.maxLength);
    parts << sqlType;
    
    // Identity (auto-increment)
    if (column.isAutoIncrement) {
        parts << "IDENTITY(1,1)";
    }
    
    // Nullability
    if (!column.isNullable) {
        parts << "NOT NULL";
    } else {
        parts << "NULL";
    }
    
    // Default value
    if (!column.defaultValue.isEmpty()) {
        QString defaultVal = column.defaultValue;
        
        // Handle common SQL Server defaults
        if (defaultVal.startsWith("(") && defaultVal.endsWith(")")) {
            parts << QString("DEFAULT %1").arg(defaultVal);
        } else if (defaultVal == "getdate()" || defaultVal.toLower() == "current_timestamp") {
            parts << "DEFAULT GETDATE()";
        } else if (column.qtType == "QString") {
            parts << QString("DEFAULT N'%1'").arg(defaultVal.replace("'", "''"));
        } else {
            parts << QString("DEFAULT %1").arg(defaultVal);
        }
    }
    
    return parts.join(" ");
}

QString SqlServerDdlGenerator::generatePrimaryKeyConstraint(const TableDefinition& table)
{
    if (table.primaryKeyColumns.isEmpty()) {
        return QString();
    }
    
    QStringList columnNames;
    for (const QString& columnName : table.primaryKeyColumns) {
        columnNames << escapeIdentifier(columnName);
    }
    
    QString constraintName = QString("PK_%1").arg(table.name);
    
    return QString("CONSTRAINT %1 PRIMARY KEY (%2)")
           .arg(escapeIdentifier(constraintName), columnNames.join(", "));
}

QString SqlServerDdlGenerator::escapeIdentifier(const QString& identifier)
{
    // SQL Server reserved words that need escaping
    static QStringList reservedWords = {
        "user", "order", "group", "table", "database", "schema", "column",
        "key", "primary", "foreign", "references", "constraint", "index",
        "view", "procedure", "function", "trigger", "select", "insert",
        "update", "delete", "create", "alter", "drop", "grant", "revoke"
    };
    
    if (reservedWords.contains(identifier.toLower()) || 
        identifier.contains(' ') || 
        identifier.contains('-')) {
        return QString("[%1]").arg(identifier);
    }
    
    return identifier;
}

} // namespace QxOrmQtOrm